# Generated by Django 5.1.5 on 2025-02-11 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Togarak_turlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Yonalish turlari',
            },
        ),
        migrations.CreateModel(
            name='Togaraklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='togarak_images')),
                ('manzil', models.CharField(max_length=150)),
                ('oquvchilar_soni', models.IntegerField(blank=True, null=True)),
                ('davomiyligi', models.CharField(blank=True, max_length=150, null=True)),
                ('boshlanish_sanasi', models.DateField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('body_small', models.TextField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyovut.togarak_turlari')),
            ],
            options={
                'verbose_name_plural': "Tog'araklar",
                'ordering': ['-publish_time'],
            },
        ),
    ]
