# Generated by Django 5.1.5 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0002_numbers_yangilik_va_tadbirlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Iqtibostlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('iqtibost_egasining_ismi', models.CharField(max_length=100)),
                ('iqtibost_egasining_familiyasi', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='iqtibost_images')),
                ('active', models.BooleanField(default=True)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Iqtiboslar',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='RasmlarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ustozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='ustozlar_images')),
                ('active', models.BooleanField(default=True)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tarif', models.CharField(max_length=100)),
                ('image_small', models.ImageField(upload_to='rasmlar_small')),
                ('image', models.ImageField(upload_to='rasmlar_big')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyovut.rasmlarcategory')),
            ],
        ),
    ]
