# Generated by Django 5.1.5 on 2025-02-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0003_contact_iqtibostlar_rasmlarcategory_ustozlar_rasmlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': "Bog'lanish", 'verbose_name_plural': "Bog'lanish"},
        ),
        migrations.AlterModelOptions(
            name='iqtibostlar',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Iqtibos', 'verbose_name_plural': 'Iqtiboslar'},
        ),
        migrations.AlterModelOptions(
            name='rasmlar',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='rasmlarcategory',
            options={'verbose_name': 'Rasm turlari', 'verbose_name_plural': 'Rasm turlari'},
        ),
        migrations.AlterModelOptions(
            name='togarak_turlari',
            options={'verbose_name': 'Yonalish turi', 'verbose_name_plural': 'Yonalish turlari'},
        ),
        migrations.AlterModelOptions(
            name='togaraklar',
            options={'ordering': ['-boshlanish_sanasi'], 'verbose_name': "To'garak", 'verbose_name_plural': "To'garaklar"},
        ),
        migrations.AlterModelOptions(
            name='ustozlar',
            options={'ordering': ['-publish_time'], 'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AlterModelOptions(
            name='yangilik_va_tadbirlar',
            options={'ordering': ['-boshlanish_sanasi'], 'verbose_name': 'Yangilik va tadbir', 'verbose_name_plural': 'Yangiliklar va tadbirlar'},
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='slug',
            field=models.SlugField(default='testslug', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yangilik_va_tadbirlar',
            name='slug',
            field=models.SlugField(default='testslug', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numbers',
            name='fanlar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='labaratoriyalar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='oqituvchilar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='oquvchilar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rasmlar',
            name='turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boyovut.rasmlarcategory'),
        ),
        migrations.AlterField(
            model_name='togaraklar',
            name='oquvchilar_soni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='togaraklar',
            name='turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boyovut.togarak_turlari'),
        ),
    ]
