# Generated by Django 5.1.5 on 2025-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0004_alter_contact_options_alter_iqtibostlar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasmlar',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-02 12:12'),
            preserve_default=False,
        ),
    ]
