# Generated by Django 5.1.5 on 2025-02-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0005_rasmlar_publish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasmlar',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
    ]
