# Generated by Django 5.1.5 on 2025-02-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0006_alter_rasmlar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasmlar',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
