# Generated by Django 5.1.5 on 2025-02-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0007_rasmlar_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasmlar',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
