# Generated by Django 5.1.5 on 2025-02-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0008_rasmlar_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasmlar',
            name='test',
        ),
    ]
