# Generated by Django 5.1.6 on 2025-02-14 14:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0009_remove_rasmlar_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togaraklar',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="To'garak haqida ba'tafsil"),
        ),
        migrations.AlterField(
            model_name='togaraklar',
            name='nomi',
            field=models.CharField(max_length=100, verbose_name='nomi'),
        ),
    ]
