# Generated by Django 5.1.6 on 2025-02-17 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0011_alter_togarak_turlari_options_alter_iqtibostlar_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='togaraklar',
            name='status',
            field=models.CharField(choices=[('New', "Yangi ochilgan to'garaklar"), ('Davom etayotgan', "Hozirda bo'layotgan to'garaklar"), ('Yakunlangan', "Tugagan to'garaklar")], default='new'),
        ),
        migrations.AlterField(
            model_name='togaraklar',
            name='oquvchilar_soni',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="O'quvchilar soni"),
        ),
    ]
