# Generated by Django 5.1.6 on 2025-02-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0012_togaraklar_status_alter_togaraklar_oquvchilar_soni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-publish_time'], 'verbose_name': "Bog'lanish", 'verbose_name_plural': "Bog'lanish"},
        ),
        migrations.AddField(
            model_name='contact',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yangilik_va_tadbirlar',
            name='status',
            field=models.CharField(choices=[('New', 'Yangi tadbirlar'), ('Yakunlangan', 'Yakunlangan tadbirlar')], default='yangi'),
        ),
        migrations.AlterField(
            model_name='togaraklar',
            name='status',
            field=models.CharField(choices=[('New', "Yangi ochilgan to'garaklar"), ('Davom etayotgan', "Hozirda bo'layotgan to'garaklar"), ('Yakunlangan', "Tugagan to'garaklar")], default='yangi'),
        ),
    ]
