# Generated by Django 5.1.6 on 2025-02-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0014_alter_togaraklar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangilik_va_tadbirlar',
            options={'ordering': ['boshlanish_sanasi'], 'verbose_name': 'Yangilik va tadbir', 'verbose_name_plural': 'Yangiliklar va tadbirlar'},
        ),
    ]
