# Generated by Django 5.1.6 on 2025-02-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyovut', '0015_alter_yangilik_va_tadbirlar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UstozlarTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ustoz dars beradigan fani',
                'verbose_name_plural': 'Ustoz dars beradigan fani',
            },
        ),
        migrations.AddField(
            model_name='ustozlar',
            name='turi',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='boyovut.ustozlarturi'),
            preserve_default=False,
        ),
    ]
